### PR TITLE
Fix JavaDocs in one file

### LINKED ISSUE #89: Wrong documentation in AddressBookBuilder.java
In `java/seedu/address/testutil/AddressBookBuilder.java`, the javadoc comment for the class states

```
/**
 * A utility class to help with building Addressbook objects.
 * Example usage: <br>
 *     {@code AddressBook ab = new AddressBookBuilder().withAnimal("John", "Doe").build();}
 */
```

which contradicts the actual method implementation:

```
/**
 * Adds a new {@code Animal} to the {@code AddressBook} that we are building.
 */
public AddressBookBuilder withAnimal(Animal animal) {
    addressBook.addAnimal(animal);
    return this;
}
```

### PR DESCRIPTION
**Pull request by JunCheng98**
Closes #89

### CODE REVIEW

File: src/test/java/seedu/address/testutil/ZooKeepBookBuilder.java [hunk 1]
```diff
@@ -6,7 +6,7 @@
 /**
  * A utility class to help with building ZooKeepBook objects.
  * Example usage: <br>
- *     {@code ZooKeepBook ab = new ZooKeepBookBuilder().withAnimal("John", "Doe").build();}
+ *     {@code ZooKeepBook ab = new ZooKeepBookBuilder().withAnimal(Harambe).build();}
```
Comment (lamlaaaam) [inline src/test/java/seedu/address/testutil/ZooKeepBookBuilder.java]: Parameter of withAnimal is an Animal object. Suggest to change "Harambe" to "harambe" to fit naming conventions.
