### PR TITLE
Prevent duplicate IDs and remove leading zeros

### LINKED ISSUE #106: Prevent adding animals with duplicate ids
Identical ids may result in unexpected behaviour when deleting an animal

Additional suggestion: prevent leading 0 in id because otherwise the ids 0123 and 123 technically should be the same but they arent?

### PR DESCRIPTION
**Pull request by koonweee**
- Add trims leading zeros from specified ID
- Tests and Typical Animals updated to match new ID format (no leading zeros, more than 3 digits)
Resolves #106

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -33,7 +33,7 @@
             + PREFIX_FEED_TIME + "1400 ";
 
     public static final String MESSAGE_SUCCESS = "New animal added: %1$s";
-    public static final String MESSAGE_DUPLICATE_ANIMAL = "This animal already exists in the address book";
+    public static final String MESSAGE_DUPLICATE_ANIMAL = "An animal with this ID already exists in the address book";
```
Comment (aizatazhar) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Should be zookeep book (or can just say "An animal with this ID already exists")

**Review by aizatazhar — COMMENTED** [review]
Could you also change the error message  (`MESSAGE_CONSTRAINTS` in `Id.java`) to mention that leading zeroes are not allowed?

Also need to change the default zookeepbook.json (in `SampleDataUtil.java`) animal's ids to have no leading zeroes

File: src/main/java/seedu/address/logic/commands/AddCommand.java (hunk 1 above)
Comment (koonweee) [reply src/main/java/seedu/address/logic/commands/AddCommand.java]: Error messages and json updated
